application: opengraphbox
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /OGTags
  script: index.php

- url: /opengraphbox.js
  script: opengraphbox.js

- url: /test
  script: test.html

- url: .*
  script: main.php
